### ISSUE TITLE
i have recommendation

### ISSUE THREAD

**Issue by rexsllemel** [BlueArduino20/ESP8266_WiFi_Captive_Portal#17]
it would be nice if you embed here the wifi deauther by spacehun to make it all in one tool.

I am waiting for your respond if it is capable.

**Comment by 125K** [comment]
You can do it if you want to, but I think that it's pointless. Just use two ESP8266...

**Comment by Alpha-1729** [comment]
Try this https://github.com/Alpha-1729/esp-wifi-captive-portal

**Comment by Alpha-1729** [comment]
> 
> 
> it would be nice if you embed here the wifi deauther by spacehun to make it all in one tool.
> 
> I am waiting for your respond if it is capable.

I will try.

**Comment by MALW4R3** [comment]
I'm going to continue to develop.

**Comment by adamff-dev** [comment]
@Alpha-1729 The feature of the SSID saved in the EEPROM was already implemented in the current code (the SSID isn't cleared after the reboot).

Btw, I tested your code and the passwords aren't saved properly in the EEPROM.

**Comment by Alpha-1729** [comment]
Issue will be solved after clearing the password.
Issue will be for the first time only.
I will fix this.

**Comment by Alpha-1729** [comment]
> 
> 
> @Alpha-1729 The feature of the SSID saved in the EEPROM was already implemented in the current code (the SSID isn't cleared after the reboot).
> 
> Btw, I tested your code and the passwords aren't saved properly in the EEPROM.

https://github.com/Alpha-1729/esp-wifi-captive-portal solved issue

**Comment by MALW4R3** [comment]
I think you should design it to look better. (Phishing page)

ในวันที่ อา. 23 ส.ค. 2020 22:10 Alpha-1729 <notifications@github.com>
เขียนว่า:

**Comment by adamff-dev** [comment]
@Alpha-1729 Cool! Now it works properly. Please, update the pull request you made and I'll merge it

**Comment by Alpha-1729** [comment]
I updated the pull request.
Please update the readme.

**Comment by adamff-dev** [comment]
Alright, done! Thank you for your collaboration.
