### ISSUE TITLE
I Have A Big Request

### ISSUE THREAD

**Issue by Faisal-076** [BlueArduino20/ESP8266_WiFi_Captive_Portal#27]
Sir, I Appreciate and love your project
As you have created a great project
I believe about 80% people use TP Link Router as their own Wi-Fi Device
And this time i just want to say please make a wifi captive portal of TP Link Router
I have searched a lot for the TP Link Captive Portal
But i have just founded an website that provides me such information of TP Link Captive Portal
And also founded a github project repository of the source code
But in that website they mentioned about Micro Python and i really a beginner about that thing
So please sir, make a TP Link Captive Portal by modifying the source Code
Please translate the website if you're unable to understand
[Project Website](https://medium.com/@maaami98/evil-twin-attack-for-esp8266-3abca8ae0402) 
[Github Source Code](https://github.com/maaami98/Evil-Twin-For-ESP8266)

**Comment by Alpha-1729** [comment]
You can design the captive portal with html and css  for the TP link captive portal.

**Comment by Faisal-076** [comment]
@Alpha-1729 Brother i really don't know how to do that
Please make it for me
Requesting you

**Comment by Alpha-1729** [comment]
I dont how the captive portal of a tplink look like.?

**Comment by adamff-dev** [comment]
@Faisal-076 If you want a new design, you have to learn HTML and CSS. Otherwise, this project isn't for you.

**Comment by Alpha-1729** [comment]
> 
> 
> @Faisal-076 If you want a new design, you have to learn HTML and CSS. Otherwise, this project isn't for you.

@125K Is there any way to add html and css separately in this repo.
instead of addding it  in the script.

**Comment by Faisal-076** [comment]
> Sir, I Appreciate and love your project
> As you have created a great project
> I believe about 80% people use TP Link Router as their own Wi-Fi Device
> And this time i just want to say please make a wifi captive portal of TP Link Router
> I have searched a lot for the TP Link Captive Portal
> But i have just founded an website that provides me such information of TP Link Captive Portal
> And also founded a github project repository of the source code
> But in that website they mentioned about Micro Python and i really a beginner about that thing
> So please sir, make a TP Link Captive Portal by modifying the source Code
> Please translate the website if you're unable to understand
> [Project Website](https://medium.com/@maaami98/evil-twin-attack-for-esp8266-3abca8ae0402)
> [Github Source Code](https://github.com/maaami98/Evil-Twin-For-ESP8266)
@Alpha-1729 
Brother i have mentioned here all of the information and website link
And there you can also view the tp link captive portal image about how it looks like
I also added the source code link
Please brother...make it for me and also ask the project creator for help if you needed
@125K brother also help me please

**Comment by adamff-dev** [comment]
@Alpha-1729 No, I'm afraid that's not possible.

**Comment by Faisal-076** [comment]
@125K 
@Alpha-1729 
Please brother make it for me
I have given all information about that
I Request you

**Comment by shahriarshafin** [comment]
I did it! @Faisal-076 knock me if you need.

![Screenshot_20200914-034653_CaptivePortalLogin](https://user-images.githubusercontent.com/32214710/93029591-dd08c980-f63d-11ea-91b8-870fafa64fca.jpg)

**Comment by Faisal-076** [comment]
Brother i need it

**Comment by Faisal-076** [comment]
Hlw brother i really need it

**Comment by Alpha-1729** [comment]
Nice, how did you add the image.

**Comment by shahriarshafin** [comment]
@Alpha-1729 
1.goto https://www.base64-image.de/
2.convert your image to BASE64
3.and paste the file,   img src=HERE .

**Comment by shahriarshafin** [comment]
@Faisal-076 check your mail.

**Comment by AnonDXT-XcX31** [comment]
> @Faisal-076 check your mail.

can i have the code too ????  please 
....
anonxcx31@gmail.com send it here brother
