### ISSUE TITLE
Adding image in captive portal

### ISSUE THREAD

**Issue by Alpha-1729** [BlueArduino20/ESP8266_WiFi_Captive_Portal#28]
How to add an image in the captive portal.

**Comment by adamff-dev** [comment]
You have to add the image in base64. Like this:

```
<img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA
    AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
        9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />
```

You can use this website for the conversion: https://www.base64-image.de

I suggest you using small images like icons.

**Comment by Alpha-1729** [comment]
Thanks bro.
