### ISSUE TITLE
is it possible to check the password against an stored handshake file on the esp ?! 

### ISSUE THREAD

**Issue by minanagehsalalma** [BlueArduino20/ESP8266_WiFi_Captive_Portal#3]

**Comment by minanagehsalalma** [comment]
@BlueArduino20 not even a single word ?!

**Comment by adamff-dev** [comment]
I think that's not possible. The ESP module is not a powerfull enough

**Comment by minanagehsalalma** [comment]
@BlueArduino20  even for a one single password ?

**Comment by adamff-dev** [comment]
Yeah. Why not testing the password by yourself?

**Comment by minanagehsalalma** [comment]
@BlueArduino20 cause we need to make it automated  .... can we do it using js ?

**Comment by minanagehsalalma** [comment]
@125K 

> I think that's not possible. The ESP module is not a powerfull enough

It's possible using js tho.
