### ISSUE TITLE
How can I access the passwords?

### ISSUE THREAD

**Issue by merdeux50** [BlueArduino20/ESP8266_WiFi_Captive_Portal#8]
I'm testing this on myself, I connect to the captive portal type a pass, it tells me it's uodating and redirecting. 
But how do I open a browser and navigate to the right address, my device disconnects from the fake wifi once I open a ios browser.

Please advise.

Thanks!

**Comment by merdeux50** [comment]
Figured it out, sorry I'm a noob but I really want to learn. I find this fascinating!

**Comment by Alpha-1729** [comment]
Try this https://github.com/Alpha-1729/esp-wifi-captive-portal.
With password storage capabilities.
